Provider as Docker example

diff --git a/provider/src/main/resources/com/sos/jobscheduler/provider/installation/bin/jobscheduler-provider b/provider/src/main/resources/com/sos/jobscheduler/provider/installation/bin/jobscheduler-provider
--- a/provider/src/main/resources/com/sos/jobscheduler/provider/installation/bin/jobscheduler-provider
+++ b/provider/src/main/resources/com/sos/jobscheduler/provider/installation/bin/jobscheduler-provider
@@ -1,16 +1,15 @@
 #!/usr/bin/env bash
 set -e
 
-# JobScheduler Master starter
+# JobScheduler Provider starter
 
 export JOBSCHEDULER_HOME="$(cd "$(dirname -- "$0")/../bin/.." && pwd || kill $$)"
 . "$JOBSCHEDULER_HOME/bin/internal/set-context.sh"
 declare classpathString java
 
-config=/var/opt/jobscheduler/master/config
-data=/var/opt/jobscheduler/master/data
-httpPort=4444
-masterOptions=()
+config=/var/opt/jobscheduler/provider/config
+data=/var/opt/jobscheduler/provider/data
+providerOptions=()
 javaOptions=(-XX:+UseStringDeduplication)
 log4jAsync=false
 
@@ -53,16 +52,12 @@ for arg in "$@"; do :
       data="${arg#*=}"
       shift
       ;;
-    -http-port=*)
-      httpPort="${arg#*=}"
-      shift
-      ;;
     -log4j-async)
       log4jAsync=true
       shift
       ;;
     *)
-      masterOptions+=("$arg")
+      providerOptions+=("$arg")
       shift
       ;;
   esac
@@ -95,17 +90,22 @@ if $log4jAsync; then :
   javaOptions+=("-Djobscheduler.log4j.immediateFlush=false")
 fi
 
-masterOptions+=("-config-directory=$(toSystemPath "$config" || kill $$)")
+providerOptions+=("-config-directory=$(toSystemPath "$config" || kill $$)")
 normalizedData="$(toSystemPath "$data" || kill $$)"
-masterOptions+=("-data-directory=$normalizedData")
-[ -z "$httpPort" ] || masterOptions+=("-http-port=$httpPort")
+#providerOptions+=("-data-directory=$normalizedData")
+
+live="$config/live"
+if [ ! -d "$live" ]; then :
+  echo "Missing directory $live"
+  exit 1
+fi
 
 execute=(
   "$java"
   "${javaOptions[@]}"
   -classpath "$classpathString"
-  com.sos.jobscheduler.master.MasterMain
-  "${masterOptions[@]}")
+  com.sos.jobscheduler.provider.ProviderMain
+  "${providerOptions[@]}")
 echo "${execute[@]}"
 "${execute[@]}" &
 
@@ -114,30 +114,7 @@ pidFile="$stateDir/pid"
 echo "$pid" >$pidFile
 echo PID $pid
 
-function terminate() {
-  echo Terminate JobScheduler Master
-  # Add some seconds to start Java with MasterClientMain
-  terminateTimeout=30
-  if [ "$SHELL" == "/bin/bash" ]; then
-    $JOBSCHEDULER_HOME/bin/jobscheduler-client -data-directory="$normalizedData" '{ "TYPE": "Terminate" }' &
-  else
-    "$java" -Xmx50m \
-      -Dlog4j.configurationFile=com/sos/jobscheduler/master/client/main/log4j2.xml \
-      -classpath "$classpathString" \
-      com.sos.jobscheduler.master.client.main.MasterClientMain \
-      -data-directory="$normalizedData" \
-      http://127.0.0.1:$httpPort \
-      "{ TYPE: Terminate }" >/dev/null &
-  fi
-  (sleep $terminateTimeout && kill $pid) &
-  killer=$!
-  wait $pid
-  kill $killer
-}
-
-trap "terminate" SIGTERM SIGINT SIGHUP
-wait $pid || echo "JobScheduler Master exited with exit code $?"
+wait $pid || echo "JobScheduler Provider exited with exit code $?"
 rm $pidFile
 
-trap - SIGTERM SIGINT SIGHUP
-echo -e "\n$(date --iso-8601=ns) JobScheduler Master has been shut down" >>$logs/stdouterr.log
+echo -e "\n$(date --iso-8601=ns) JobScheduler Provider has been shut down" >>$logs/stdouterr.log
