Docker

diff --git a/jobscheduler-docker/src/main/resources/com/sos/jobscheduler/install/docker/bin/prepare b/jobscheduler-docker/src/main/resources/com/sos/jobscheduler/install/docker/bin/prepare
--- a/jobscheduler-docker/src/main/resources/com/sos/jobscheduler/install/docker/bin/prepare
+++ b/jobscheduler-docker/src/main/resources/com/sos/jobscheduler/install/docker/bin/prepare
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 set -e
 
+installTgz=jobscheduler-*install-[0-9]*.tgz
+
 for arg in "$@"; do :
   case "$arg" in
     *)
@@ -14,19 +16,28 @@ if [ -d build ] && [ ! -f build/bin/prepare ]; then :
   echo "Subdirectory build seems not to be created by jobscheduler-docker. Missing file build/bin/prepare. Exiting"
   exit 1
 fi
+dockerTgz="jobscheduler-docker-[0-9]*.tgz"
+ls $dockerTgz >/dev/null || {
+  echo "Missing file '$dockerTgz'"
+  exit 1
+}
+installTgz="jobscheduler-*install-[0-9]*.tgz"
+ls $installTgz >/dev/null || {
+  echo "Missing file '$installTgz'"
+  exit 1
+}
 
 rm -rf build
 tar xzf jobscheduler-docker-[0-9]*.tgz
-cp jobscheduler-*install-[0-9]*.tgz build/ || {
-  echo "Missing installation file jobscheduler-install-x.y.tgz"
-  exit 1
-}
+cp jobscheduler-*install-[0-9]*.tgz build/
 build/bin/prepare-volumes
 
 [ -f docker-compose.yml ] || ln -sf build/docker-compose.yml .
 
-docker-compose build
 docker-compose down
+# Let Docker not accumulate old images:
+docker-compose rm -v
+docker-compose build
 
 echo
 echo Start with: docker-compose up
