Rename as JS7: remaining

diff --git a/jobscheduler-docker/src/main/resources/js7/install/docker/bin/prepare b/jobscheduler-docker/src/main/resources/js7/install/docker/bin/prepare
--- a/jobscheduler-docker/src/main/resources/js7/install/docker/bin/prepare
+++ b/jobscheduler-docker/src/main/resources/js7/install/docker/bin/prepare
@@ -3,8 +3,8 @@ set -e
 
 cd "$(cd "$(realpath "${0%/*}")"/../../build/bin/../.. && pwd)"
 
-dockerTgz="$(ls jobscheduler-docker-[0-9]*.tgz)"
-installTgz=($(ls jobscheduler-*install-[0-9]*.tgz))
+dockerTgz="$(ls js7-docker-[0-9]*.tgz)"
+installTgz=($(ls js7-*install-[0-9]*.tgz))
 
 for arg in "$@"; do :
   case "$arg" in
@@ -16,7 +16,7 @@ for arg in "$@"; do :
 done
 
 if [ -d build ] && [ ! -f build/bin/prepare ]; then :
-  echo "Subdirectory build seems not to be created by jobscheduler-docker. Missing file build/bin/prepare. Exiting"
+  echo "Subdirectory build seems not to be created by js7-docker. Missing file build/bin/prepare. Exiting"
   exit 1
 fi
 
@@ -30,7 +30,7 @@ build/bin/prepare-volumes
 
 docker-compose down --remove-orphans
 # Let Docker not accumulate old images:
-docker rmi --jobscheduler &>/dev/null || true
+docker rmi --js7 &>/dev/null || true
 docker-compose build --parallel
 docker-compose up --no-start
 
